global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'websocket-app'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics/'
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # TODO: provide add opensource alert manager later
